// Generated by CoffeeScript 1.6.3
var AbstractProcessingHandler, ConsoleLogHandler, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AbstractProcessingHandler = require('./AbstractProcessingHandler');

ConsoleLogHandler = (function(_super) {
  __extends(ConsoleLogHandler, _super);

  function ConsoleLogHandler() {
    _ref = ConsoleLogHandler.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  ConsoleLogHandler.prototype.write = function(record, cb) {
    console.log(record.formatted);
    if (cb instanceof Function) {
      return cb(void 0, record, this);
    }
  };

  return ConsoleLogHandler;

})(AbstractProcessingHandler);

module.exports = ConsoleLogHandler;

/*
//@ sourceMappingURL=ConsoleLogHandler.map
*/
