// Generated by CoffeeScript 1.6.3
"use strict";
var Abstractprocessinghandler, TestHandler,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Abstractprocessinghandler = require('./AbstractProcessingHandler');

TestHandler = (function(_super) {
  __extends(TestHandler, _super);

  function TestHandler() {
    TestHandler.__super__.constructor.apply(this, arguments);
    this.records = [];
  }

  TestHandler.prototype.write = function(record, cb) {
    this.records.push(record.formatted);
    if (cb instanceof Function) {
      return cb(void 0, this.records, record, this);
    }
  };

  return TestHandler;

})(Abstractprocessinghandler);

module.exports = TestHandler;

/*
//@ sourceMappingURL=TestHandler.map
*/
