// Generated by IcedCoffeeScript 1.6.3-j
(function() {
  var monolog, _;

  monolog = exports;

  _ = require('underscore');

  monolog.Logger = (function() {
    function Logger() {}

    Logger.DEBUG = 100;

    Logger.INFO = 200;

    Logger.NOTICE = 250;

    Logger.WARNING = 300;

    Logger.ERROR = 400;

    Logger.CRITICAL = 500;

    Logger.ALERT = 550;

    Logger.EMERGENCY = 600;

    Logger.API = 1;

    Logger.levels = {
      100: 'DEBUG',
      200: 'INFO',
      250: 'NOTICE',
      300: 'WARNING',
      400: 'ERROR',
      500: 'CRITICAL',
      550: 'ALERT',
      600: 'EMERGENCY'
    };

    return Logger;

  })();

}).call(this);
