// Generated by CoffeeScript 1.6.3
"use strict";
var monolog;

monolog = {
  Logger: require('./Logger'),
  handler: {
    AbstractHandler: require('./handler/AbstractHandler'),
    AbstractProcessingHandler: require('./handler/AbstractProcessingHandler'),
    ConsoleLogHandler: require('./handler/ConsoleLogHandler'),
    NullHandler: require('./handler/NullHandler'),
    TestHandler: require('./handler/TestHandler'),
    StreamHandler: require('./handler/StreamHandler')
  },
  formatter: {
    LineFormatter: require('./formatter/LineFormatter'),
    NormalizerFormatter: require('./formatter/NormalizerFormatter')
  }
};

module.exports = monolog;

/*
//@ sourceMappingURL=monolog.map
*/
