// Generated by CoffeeScript 1.6.3
"use strict";
var monolog;

monolog = {
  Logger: require('./Logger'),
  handler: {
    AbstractHandler: require('./handler/AbstractHandler'),
    AbstractProcessingHandler: require('./handler/AbstractProcessingHandler'),
    ConsoleLogHandler: require('./handler/ConsoleLogHandler'),
    NullHandler: require('./handler/NullHandler'),
    TestHandler: require('./handler/TestHandler'),
    StreamHandler: require('./handler/StreamHandler'),
    CouchDBHandler: require('./handler/CouchDBHandler')
  },
  formatter: {
    LineFormatter: require('./formatter/LineFormatter'),
    NormalizerFormatter: require('./formatter/NormalizerFormatter')
  },
  processor: {
    WebProcessor: require('./processor/WebProcessor'),
    ExpressProcessor: require('./processor/ExpressProcessor')
  }
};

monolog.create = function() {
  return (function(func, args, ctor) {
    ctor.prototype = func.prototype;
    var child = new ctor, result = func.apply(child, args);
    return Object(result) === result ? result : child;
  })(monolog.Logger, arguments, function(){});
};

module.exports = monolog;

/*
//@ sourceMappingURL=monolog.map
*/
