// Generated by CoffeeScript 1.6.3
"use strict";
var AbstractFormatter;

AbstractFormatter = (function() {
  function AbstractFormatter() {}

  AbstractFormatter.prototype.format = function(record) {
    throw "not implemented";
  };

  AbstractFormatter.prototype.formatBatch = function(records) {
    var _this = this;
    return records.map(function(r) {
      return _this.format(r);
    }).join();
  };

  return AbstractFormatter;

})();

module.exports = AbstractFormatter;

/*
//@ sourceMappingURL=AbstractFormatter.map
*/
