// Generated by CoffeeScript 1.6.3
"use strict";
var FormatterInterface;

FormatterInterface = (function() {
  function FormatterInterface() {}

  FormatterInterface.prototype.format = function(record) {
    throw "not implemented";
  };

  FormatterInterface.prototype.formatBatch = function(records) {
    var _this = this;
    return records.map(function(r) {
      return _this.format(r);
    }).join();
  };

  return FormatterInterface;

})();

module.exports = FormatterInterface;

/*
//@ sourceMappingURL=AbstractFormatter.map
*/
