// Generated by CoffeeScript 1.6.3
"use strict";
var FormatterInterface;

FormatterInterface = (function() {
  function FormatterInterface() {}

  FormatterInterface.prototype.format = function(record) {};

  FormatterInterface.prototype.formatBatch = function(records) {};

  return FormatterInterface;

})();

module.exports = FormatterInterface;

/*
//@ sourceMappingURL=FormatterInterface.map
*/
