// Generated by CoffeeScript 1.6.3
"use strict";
var AbstractFormatter, JSONFormatter, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

AbstractFormatter = require("./AbstractFormatter");

JSONFormatter = (function(_super) {
  __extends(JSONFormatter, _super);

  function JSONFormatter() {
    _ref = JSONFormatter.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  JSONFormatter.prototype.format = function(record) {
    return {
      level: record.level,
      level_name: record.level_name,
      channel: record.channel,
      datetime: record.date,
      message: record.message,
      extra: record.extra,
      context: record.context
    };
  };

  return JSONFormatter;

})(AbstractFormatter);

module.exports = JSONFormatter;

/*
//@ sourceMappingURL=JSONFormatter.map
*/
